# Generated by Django 3.0.2 on 2020-02-06 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('westargram', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
    ]
