# Generated by Django 3.0.2 on 2020-02-07 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('westargram', '0002_auto_20200206_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='username',
        ),
    ]
